on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Checks out the code from your repository

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest my_test.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
        continue-on-error: true
